import express from "express";
import { db } from "../../database/db.js";
import { audit, optionalIdentity, requirePermission, requireStaffAuth } from "../auth.js";

const router=express.Router();
function map(row){return{id:row.id,recipientType:row.recipient_type,recipientId:row.recipient_id,orderId:row.order_id,titleEn:row.title_en,titleHi:row.title_hi||row.title_en,messageEn:row.message_en,messageHi:row.message_hi||row.message_en,type:row.type,isRead:Boolean(row.is_read),createdAt:row.created_at,readAt:row.read_at};}
async function identity(req,res,next){return optionalIdentity(req,res,()=>{if(!req.customer&&!req.staff)return res.status(401).json({error:"Authentication is required."});next();});}
function scope(req){if(req.customer)return{where:"recipient_type='CUSTOMER' AND recipient_id=?",params:[req.customer.id]};const role=String(req.staff.role_code||"").toUpperCase();return{where:"((recipient_type='USER' AND recipient_id=?) OR (recipient_type='ROLE' AND (recipient_id=? OR recipient_id IS NULL)))",params:[req.staff.id,req.staff.role_id]};}

router.get("/notifications",identity,async(req,res)=>{try{const limit=Math.min(100,Math.max(1,Number(req.query.limit)||50));const target=scope(req);const rows=await db.query(`SELECT * FROM notification WHERE ${target.where} ORDER BY created_at DESC LIMIT ?`,[...target.params,limit]);const count=await db.get(`SELECT COUNT(*) unread FROM notification WHERE ${target.where} AND is_read=0`,target.params);res.json({notifications:rows.map(map),unreadCount:Number(count.unread)});}catch(error){console.error("Notification list failed:",error.message);res.status(500).json({error:"Unable to load notifications."});}});

router.post("/notifications",requireStaffAuth,requirePermission("settings"),async(req,res)=>{const type=String(req.body?.recipientType||"").toUpperCase();const id=req.body?.recipientId===undefined?null:Number(req.body.recipientId);if(!["CUSTOMER","USER","ROLE"].includes(type)||(!id&&type!=="ROLE"))return res.status(400).json({error:"A valid recipient type and ID are required."});const title=String(req.body?.titleEn||"").trim(),message=String(req.body?.messageEn||"").trim();if(!title||!message)return res.status(400).json({error:"Title and message are required."});try{const result=await db.execute("INSERT INTO notification (recipient_type,recipient_id,recipient_phone,order_id,title_en,title_hi,message_en,message_hi,type) VALUES (?,?,?,?,?,?,?,?,?)",[type,id,String(req.body.recipientPhone||""),req.body.orderId||null,title,String(req.body.titleHi||""),message,String(req.body.messageHi||""),String(req.body.type||"SYSTEM")]);await audit("USER",req.staff.id,"CREATE_NOTIFICATION","notification",result.lastID,{recipientType:type,recipientId:id},req);res.status(201).json({success:true,id:result.lastID});}catch(error){console.error("Notification create failed:",error.message);res.status(500).json({error:"Unable to create notification."});}});

router.put("/notifications/:id/read",identity,async(req,res)=>{const target=scope(req);const result=await db.execute(`UPDATE notification SET is_read=1,read_at=CURRENT_TIMESTAMP WHERE id=? AND ${target.where}`,[req.params.id,...target.params]);if(!result.changes)return res.status(404).json({error:"Notification not found."});res.json({success:true});});
router.put("/notifications/read-all",identity,async(req,res)=>{const target=scope(req);await db.execute(`UPDATE notification SET is_read=1,read_at=COALESCE(read_at,CURRENT_TIMESTAMP) WHERE ${target.where}`,target.params);res.json({success:true});});

export default router;
