import express from "express";
import { db } from "../../database/db.js";
import { audit, canAdminister, hashPassword, normalizeMobile, requirePermission, requireStaffAuth, toPublicStaff } from "../auth.js";

const router=express.Router();
router.use(["/roles","/users","/staff"],requireStaffAuth,requirePermission("staff"));
const SELECT=`SELECT u.id,u.full_name,u.phone_number,u.email,u.password_hash,u.role_id,u.status,u.is_master_admin,r.name AS role_name,r.description AS role_description,GROUP_CONCAT(DISTINCT p.code) AS permission_codes,ds.id AS delivery_staff_id,ds.status AS delivery_status,ds.vehicle_type,ds.vehicle_number FROM "user" u LEFT JOIN role r ON r.id=u.role_id LEFT JOIN role_permission rp ON rp.role_id=r.id LEFT JOIN permission p ON p.id=rp.permission_id LEFT JOIN delivery_staff ds ON ds.user_id=u.id`;
function mapped(row){return{...toPublicStaff(row),deliveryStaffId:row.delivery_staff_id||null,deliveryStatus:row.delivery_status||null,vehicleType:row.vehicle_type||"",vehicleNumber:row.vehicle_number||""};}
async function roleFrom(body){const value=body.roleId??body.role??body.roleCode;if(value===undefined)return null;return Number.isInteger(Number(value))?db.get("SELECT * FROM role WHERE id=?",[Number(value)]):db.get("SELECT * FROM role WHERE upper(name)=upper(?)",[String(value)]);}
function privileged(role){return["MASTER_ADMIN","ADMIN"].includes(String(role?.name||"").toUpperCase());}
function deliveryRole(role){return["DELIVERY","RIDER"].includes(String(role?.name||"").toUpperCase());}

router.get("/roles",async(_req,res)=>{const roles=await db.query(`SELECT r.*,GROUP_CONCAT(p.code) permission_codes FROM role r LEFT JOIN role_permission rp ON rp.role_id=r.id LEFT JOIN permission p ON p.id=rp.permission_id GROUP BY r.id ORDER BY r.id`);res.json(roles.map(role=>({...role,permissions:String(role.permission_codes||"").split(',').filter(Boolean)})));});
router.get("/users",async(_req,res)=>res.json((await db.query(`${SELECT} GROUP BY u.id ORDER BY u.id`)).map(mapped)));
router.get("/staff",async(_req,res)=>res.json((await db.query(`${SELECT} WHERE lower(r.name)<>'user' GROUP BY u.id ORDER BY u.id`)).map(mapped)));

router.post("/staff",async(req,res)=>{try{const name=String(req.body?.name||"").trim(),mobile=normalizeMobile(req.body?.mobile),password=String(req.body?.password||"");const role=await roleFrom(req.body||{});if(name.length<2||mobile.length!==10||password.length<10||password.length>128||!role)return res.status(400).json({error:"Valid name, mobile, 10-128 character password, and role are required."});if(privileged(role)&&!canAdminister(req.staff))return res.status(403).json({error:"Administrator authority is required for this role."});if(String(role.name).toUpperCase()==="MASTER_ADMIN")return res.status(403).json({error:"Master administrator accounts cannot be created through this API."});const result=await db.transaction(async tx=>{const inserted=await tx.execute(`INSERT INTO "user" (full_name,phone_number,email,password_hash,role_id,status,is_master_admin) VALUES (?,?,?,?,?,'Active',0)`,[name,mobile,String(req.body.email||""),await hashPassword(password),role.id]);if(deliveryRole(role))await tx.execute("INSERT INTO delivery_staff (user_id,name,phone,status,vehicle_type,vehicle_number) VALUES (?,?,?,'ACTIVE',?,?)",[inserted.lastID,name,mobile,String(req.body.vehicleType||""),String(req.body.vehicleNumber||"")]);return inserted.lastID;});await audit("USER",req.staff.id,"CREATE_STAFF","user",result,{role:role.name},req);res.status(201).json({success:true,staff:mapped(await db.get(`${SELECT} WHERE u.id=? GROUP BY u.id`,[result]))});}catch(error){console.error("Staff create failed:",error.message);res.status(error.code==="SQLITE_CONSTRAINT"?409:500).json({error:error.code==="SQLITE_CONSTRAINT"?"Phone number already exists.":"Unable to create staff."});}});

router.put("/staff/:id",async(req,res)=>{try{const id=Number(req.params.id),current=await db.get(`${SELECT} WHERE u.id=? GROUP BY u.id`,[id]);if(!current)return res.status(404).json({error:"Staff member not found."});if(current.is_master_admin&&id!==req.staff.id)return res.status(403).json({error:"Master administrator cannot be modified."});const role=await roleFrom(req.body||{})||await db.get("SELECT * FROM role WHERE id=?",[current.role_id]);if(privileged(role)&&!canAdminister(req.staff))return res.status(403).json({error:"Administrator authority is required for this role."});if(String(role.name).toUpperCase()==="MASTER_ADMIN"&&!current.is_master_admin)return res.status(403).json({error:"Cannot promote to master administrator."});const name=String(req.body.name??current.full_name).trim(),mobile=req.body.mobile===undefined?current.phone_number:normalizeMobile(req.body.mobile),status=["active","enabled"].includes(String(req.body.status??current.status).toLowerCase())?"Active":"Disabled";if(name.length<2||mobile.length!==10)return res.status(400).json({error:"Valid name and mobile are required."});if(req.body.password!==undefined&&(String(req.body.password).length<10||String(req.body.password).length>128))return res.status(400).json({error:"Password must be 10-128 characters."});await db.transaction(async tx=>{const password=req.body.password?await hashPassword(req.body.password):current.password_hash;await tx.execute(`UPDATE "user" SET full_name=?,phone_number=?,email=?,password_hash=?,role_id=?,status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`,[name,mobile,String(req.body.email??current.email??""),password,role.id,status,id]);if(deliveryRole(role))await tx.execute(`INSERT INTO delivery_staff (user_id,name,phone,status,vehicle_type,vehicle_number) VALUES (?,?,?,? ,?,?) ON CONFLICT(user_id) DO UPDATE SET name=excluded.name,phone=excluded.phone,status=excluded.status,vehicle_type=excluded.vehicle_type,vehicle_number=excluded.vehicle_number,updated_at=CURRENT_TIMESTAMP`,[id,name,mobile,status==="Active"?"ACTIVE":"INACTIVE",String(req.body.vehicleType??current.vehicle_type??""),String(req.body.vehicleNumber??current.vehicle_number??"")]);else if(current.delivery_staff_id)await tx.execute("UPDATE delivery_staff SET status='INACTIVE',updated_at=CURRENT_TIMESTAMP WHERE user_id=?",[id]);if(status!=="Active")await tx.execute("UPDATE user_session SET revoked_at=CURRENT_TIMESTAMP WHERE user_id=? AND revoked_at IS NULL",[id]);});await audit("USER",req.staff.id,"UPDATE_STAFF","user",id,{role:role.name,status},req);res.json({success:true,staff:mapped(await db.get(`${SELECT} WHERE u.id=? GROUP BY u.id`,[id]))});}catch(error){console.error("Staff update failed:",error.message);res.status(error.code==="SQLITE_CONSTRAINT"?409:500).json({error:error.code==="SQLITE_CONSTRAINT"?"Phone number already exists.":"Unable to update staff."});}});

router.delete("/staff/:id",async(req,res)=>{const id=Number(req.params.id);const current=await db.get("SELECT * FROM \"user\" WHERE id=?",[id]);if(!current)return res.status(404).json({error:"Staff member not found."});if(current.is_master_admin)return res.status(403).json({error:"Master administrator cannot be disabled."});await db.transaction(async tx=>{await tx.execute("UPDATE \"user\" SET status='Disabled',updated_at=CURRENT_TIMESTAMP WHERE id=?",[id]);await tx.execute("UPDATE delivery_staff SET status='INACTIVE',updated_at=CURRENT_TIMESTAMP WHERE user_id=?",[id]);await tx.execute("UPDATE user_session SET revoked_at=CURRENT_TIMESTAMP WHERE user_id=? AND revoked_at IS NULL",[id]);});await audit("USER",req.staff.id,"DISABLE_STAFF","user",id,{},req);res.json({success:true});});

export default router;
