import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    title: "Swastik Supermarket",
    home: "Home",
    shop: "Shop",
    cart: "Cart",
    account: "Account",
    weeklySpecial: "WEEKLY SPECIAL",
    organicProduceTitle: "Up to 40% OFF\non Fresh Organic Produce",
    shopNow: "Shop Now",
    pantrySavings: "STAPLES SAVINGS",
    pantrySavingsTitle: "Flat ₹ 200 Cashback\non Monthly Grocery",
    claimOffer: "Claim Offer",
    fruits: "Fruits",
    dairy: "Dairy",
    bakery: "Bakery",
    frozen: "Frozen",
    drinks: "Drinks",
    beverages: "Beverages",
    hygiene: "Hygiene",
    vegetables: "Vegetables",
    staples: "Staples",
    all: "All",
    household: "Household",
    personalCare: "Personal Care",
    featuredProducts: "Featured Products",
    viewAll: "View All",
    offerZone: "OFFER ZONE",
    flashSaleTitle: "Weekend Flash Sale!",
    flashSaleDesc: "Flash sales on over 500+ items every Saturday and Sunday.",
    upTo60: "UP TO 60% OFF",
    endsIn: "Ends in 08h : 45m : 12s",
    endsInShop: "Ending in 02h 45m 12s",
    endsInLabel: "Ending in",
    decimals: "02h 45m 06s",
    customerSay: "What Our Customers Say",
    testimonial1: '"The quality of vegetables is unmatched. I always find everything fresh and the delivery is incredibly fast. Swastik has become our primary source for all groceries."',
    testimonial2: '"Love the offer zone! I save a lot on my monthly groceries using their app. The Hindi interface makes it so easy for my parents to order too."',
    testimonial3: '"Impressive range of organic products. The packaging is minimal and eco-friendly. Customer support is very responsive whenever I have an inquiry."',
    visitStore: "Visit Our Main Store",
    visitStoreDesc: "Experience the quality in person. Our flagship store features a live bakery and a specialized organic section.",
    storeAddressTitle: "Main Market, Sector 12",
    storeAddressSub: "New Delhi, Delhi 110075",
    openDaily: "Open Daily",
    storeHours: "08:00 AM - 10:00 PM",
    tollFree: "Toll Free: 1800 123 4567",
    getDirections: "Get Directions",
    searchPlaceholder: "Search for groceries, snacks, household...",
    filters: "Filters",
    sort: "Sort",
    addToCart: "Add to Cart",
    add: "Add",
    added: "Added",
    yourCart: "Your Shopping Cart",
    itemsCount: "Items",
    qty: "Qty",
    shippingInfo: "Shipping Information",
    fullName: "Full Name",
    phoneNumber: "Phone Number",
    deliveryAddress: "Delivery Address",
    orderSummary: "Order Summary",
    subtotal: "Subtotal",
    deliveryFee: "Delivery Fee",
    gst: "GST (18%)",
    grandTotal: "Grand Total",
    paymentMethod: "Payment Method",
    selectPaymentMethod: "Select Payment Method",
    creditCard: "Cards (Credit/Debit)",
    creditCardSub: "Visa, Mastercard, RuPay",
    upiPay: "UPI Payments",
    upiPaySub: "GPay, PhonePe, Paytm",
    cashOnDelivery: "Cash on Delivery",
    cashOnDeliverySub: "Pay cash on delivery",
    unavailable: "UNAVAILABLE",
    placeOrder: "PLACE ORDER",
    payNow: "PAY NOW",
    termsAgree: "By placing your order, you agree to our Terms and Conditions.",
    couponCode: "Coupon Code",
    appliedSuccess: "Code 'SUPER20' applied successfully!",
    super20Applied: "SUPER20 Applied",
    super20Desc: "You saved ₹ 520 on this order!",
    myAccount: "My Account",
    accountDesc: "Manage your profile, orders, and preferences",
    logout: "Logout",
    profileManagement: "Profile Management",
    editInfo: "Edit Info",
    security: "Security",
    securityDesc: "Keep your account safe by updating your password regularly.",
    currentPassword: "Current Password",
    newPassword: "New Password",
    updatePassword: "Update Password",
    myOrders: "My Orders list",
    orderIdTitle: "Order ID",
    dateTitle: "Date",
    statusTitle: "Status",
    totalTitle: "Total",
    actionTitle: "Action",
    details: "Details",
    preferences: "Preferences",
    languagePref: "Default Language",
    notificationPref: "Notification Settings",
    orderUpdates: "Order Updates",
    promotionalOffers: "Promotional Offers",
    inTransit: "In Transit",
    delivered: "Delivered",
    flashSales: "Flash Sales",
    weekendMegaSale: "WEEKEND MEGA SALE",
    dealOfDay: "Deals of the Day: Up to 60% OFF",
    dealOfDayDesc: "Stock up your pantry with our biggest discounts ever. Valid for today only.",
    buy1get1: "Buy 1 Get 1",
    householdSupplies: "On all Household Supplies",
    exploreCategories: "Explore Categories",
    bankOffers: "Bank Offers",
    bankOffersDesc: "Flat 10% Instant Discount on HDFC Cards",
    allDeals: "All Deals",
    comboDeals: "Combo Deals",
    breakfastCombo: "Breakfast Combo",
    breakfastComboDesc: "Milk 1L + Bread + Eggs (6pcs)",
    cleaningKit: "Cleaning Kit",
    cleaningKitDesc: "Floor Cleaner + Dishwash Gel + Sponge",
    addCombo: "Add Combo",
    initializing: "Initializing",
    dailyEssentials: "Your daily essentials, delivered.",
    contactUs: "Contact Us",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    storeLocator: "Store Locator",
    deliveryDetails: "Delivery Details",
    priority: "Priority",
    distanceText: "Distance: 5.2 KM",
    distanceDesc: "Delivery charges are calculated based on your distance from our nearest distribution center.",
    secureCheckoutTitle: "Secure Checkout",
    secureCheckoutDesc: "Your transaction is encrypted and 100% safe.",
    couponDiscountLabel: "Coupon Discount (SUPER20)",
    totalSavingsLabel: "Total Savings: ₹ 520",
    change: "CHANGE",
    applyBtn: "APPLY",
    packOf5: "Pack of 5kg",
    packOf1: "1 Litre Bottle",
    packOfChoc: "85% Cocoa - 100g",
    basmatiText: "Premium Basmati Rice",
    oliveOilText: "Extra Virgin Olive Oil",
    darkChocText: "Gourmet Dark Chocolate"
  },
  hi: {
    title: "स्वास्तिक सुपरमार्केट",
    home: "होम",
    shop: "दुकान",
    cart: "कार्ट",
    account: "खाता",
    weeklySpecial: "साप्ताहिक विशेष",
    organicProduceTitle: "ताज़ी जैविक उपज पर\n40% तक की छूट",
    shopNow: "अभी खरीदें",
    pantrySavings: "राशन बचत",
    pantrySavingsTitle: "मासिक राशन पर\nसीधे ₹ 200 कैशबैक",
    claimOffer: "ऑफ़र प्राप्त करें",
    fruits: "फल",
    dairy: "डेयरी",
    bakery: "बेकरी",
    frozen: "फ़्रोजन",
    drinks: "पेय",
    beverages: "पेय पदार्थ",
    hygiene: "स्वच्छता",
    vegetables: "सब्ज़ियां",
    staples: "मुख्य खाद्य",
    all: "सभी",
    household: "घरेलू सामान",
    personalCare: "व्यक्तिगत देखभाल",
    featuredProducts: "विशेष उत्पाद",
    viewAll: "सभी देखें",
    offerZone: "ऑफ़र ज़ोन",
    flashSaleTitle: "सप्ताहांत फ़्लैश सेल!",
    flashSaleDesc: "प्रत्येक शनिवार और रविवार को 500+ से अधिक वस्तुओं पर फ़्लैश सेल।",
    upTo60: "60% तक की छूट",
    endsIn: "समाप्त होने में: 08घं : 45मि : 12से",
    endsInShop: "समाप्त होने में 02घं 45मि 12से",
    endsInLabel: "समाप्त होने में",
    decimals: "02घं 45मि 06से",
    customerSay: "हमारे ग्राहक क्या कहते हैं",
    testimonial1: '"सब्जियों की गुणवत्ता लाजवाब है। मुझे हमेशा सब कुछ ताज़ा मिलता है और डिलीवरी अविश्वसनीय रूप से तेज़ है। स्वास्तिक हमारी सभी किराने की वस्तुओं का प्राथमिक स्रोत बन गया है।"',
    testimonial2: '"ऑफ़र ज़ोन बहुत पसंद आया! मैं उनके ऐप का उपयोग करके अपने मासिक राशन पर बहुत बचत करती हूँ। हिंदी इंटरफ़ेस मेरे माता-पिता के लिए ऑर्डर करना बहुत आसान बना देता है।"',
    testimonial3: '"जैविक उत्पादों की प्रभावशाली श्रृंखला। पैकेजिंग न्यूनतम और पर्यावरण के अनुकूल है। जब भी मेरी कोई पूछताछ होती है तो ग्राहक सहायता बहुत तत्पर रहती है।""',
    visitStore: "हमारे मुख्य स्टोर पर आएं",
    visitStoreDesc: "स्वयं आकर गुणवत्ता का अनुभव करें। हमारे प्रमुख स्टोर में एक लाइव बेकरी और एक विशेष जैविक अनुभाग है।",
    storeAddressTitle: "मेन मार्केट, सेक्टर 12",
    storeAddressSub: "नई दिल्ली, दिल्ली 110075",
    openDaily: "रोजाना खुला है",
    storeHours: "सुबह 08:00 बजे - रात 10:00 बजे",
    tollFree: "टोल फ्री: 1800 123 4567",
    getDirections: "दिशा-निर्देश प्राप्त करें",
    searchPlaceholder: "किराने का सामान, स्नैक्स, घरेलू सामान खोजें...",
    filters: "फ़िल्टर्स",
    sort: "क्रमबद्ध करें",
    addToCart: "कार्ट में जोड़ें",
    add: "जोड़ें",
    added: "जोड़ा गया",
    yourCart: "आपकी शॉपिंग कार्ट",
    itemsCount: "वस्तुएं",
    qty: "मात्रा",
    shippingInfo: "शिपिंग विवरण",
    fullName: "पूरा नाम",
    phoneNumber: "फ़ोन नंबर",
    deliveryAddress: "वितरण का पता",
    orderSummary: "ऑर्डर सारांश",
    subtotal: "उप-योग",
    deliveryFee: "वितरण शुल्क",
    gst: "जीएसटी (18%)",
    grandTotal: "कुल योग",
    paymentMethod: "भुगतान का प्रकार",
    selectPaymentMethod: "भुगतान विधि चुनें",
    creditCard: "कार्ड (क्रेडिट/डेबिट)",
    creditCardSub: "वीज़ा, मास्टरकार्ड, रुपे",
    upiPay: "यूपीआई भुगतान",
    upiPaySub: "जीपे, फ़ोनपे, पेटीएम",
    cashOnDelivery: "कैश ऑन डिलीवरी",
    cashOnDeliverySub: "डिलिवरी के समय नकद भुगतान करें",
    unavailable: "अनुपलब्ध",
    placeOrder: "ऑर्डर सबमिट करें",
    payNow: "अभी भुगतान करें",
    termsAgree: "ऑर्डर देकर, आप हमारे नियम और शर्तों से सहमत होते हैं।",
    couponCode: "कूपन कोड",
    appliedSuccess: "कूपन कोड 'SUPER20' सफलतापूर्वक लागू किया गया!",
    super20Applied: "SUPER20 लागू",
    super20Desc: "आपने इस ऑर्डर पर ₹ 520 बचाए!",
    myAccount: "मेरा खाता",
    accountDesc: "अपने प्रोफाइल, ऑर्डर और प्राथमिकताओं को प्रबंधित करें",
    logout: "लॉगआउट",
    profileManagement: "प्रोफ़ाइल प्रबंधन",
    editInfo: "संपादित करें",
    security: "सुरक्षा",
    securityDesc: "नियमित रूप से अपना पासवर्ड अपडेट करके अपने खाते को सुरक्षित रखें।",
    currentPassword: "वर्तमान पासवर्ड",
    newPassword: "नया पासवर्ड",
    updatePassword: "पासवर्ड बदलें",
    myOrders: "मेरी ऑर्डर सूची",
    orderIdTitle: "ऑर्डर आईडी",
    dateTitle: "दिनांक",
    statusTitle: "स्थिति",
    totalTitle: "कुल",
    actionTitle: "कार्रवाई",
    details: "विवरण",
    preferences: "प्राथमिकताएं",
    languagePref: "डिफ़ॉल्ट भाषा",
    notificationPref: "अधिसूचना सेटिंग्स",
    orderUpdates: "ऑर्डर अपडेट",
    promotionalOffers: "प्रचारक ऑफ़र",
    inTransit: "पारगमन में",
    delivered: "पहुंचा दिया",
    flashSales: "फ़्लैश सेल",
    weekendMegaSale: "सप्ताहांत मेगा सेल",
    dealOfDay: "आज के बेहतरीन ऑफ़र: 60% तक की छूट",
    dealOfDayDesc: "अब तक की सबसे बड़ी छूट के साथ अपनी रसोई का राशन भरें। केवल आज के लिए मान्य।",
    buy1get1: "एक खरीदें एक मुफ़्त (BOGO)",
    householdSupplies: "सभी घरेलू सामानों पर",
    exploreCategories: "श्रेणियां देखें",
    bankOffers: "बैंक ऑफ़र्स",
    bankOffersDesc: "HDFC कार्ड्स पर सीधे 10% की त्वरित छूट",
    allDeals: "सभी डील्स",
    comboDeals: "कॉम्बो ऑफ़र्स",
    breakfastCombo: "नाश्ता कॉम्बो",
    breakfastComboDesc: "दूध 1L + ब्रेड + अंडे (6 नग)",
    cleaningKit: "क्लीनिंग किट",
    cleaningKitDesc: "फ्लोर क्लीनर + डिशवॉश जेल + स्पंज",
    addCombo: "कॉम्बो जोड़ें",
    initializing: "शुरू किया जा रहा है",
    dailyEssentials: "आपकी दैनिक आवश्यकताएं, सीधे घर तक।",
    contactUs: "संपर्क करें",
    privacyPolicy: "गोपनीयता नीति",
    termsOfService: "सेवा की शर्तें",
    storeLocator: "स्टोर लोकेटर",
    deliveryDetails: "वितरण विवरण",
    priority: "प्राथमिकता",
    distanceText: "दूरी: 5.2 किलोमीटर",
    distanceDesc: "वितरण शुल्क की गणना हमारे निकटतम वितरण केंद्र से आपकी दूरी के आधार पर की जाती है।",
    secureCheckoutTitle: "सुरक्षित चेकआउट",
    secureCheckoutDesc: "आपका लेनदेन एन्क्रिप्टेड और सुरक्षित है।",
    couponDiscountLabel: "कूपन छूट (SUPER20)",
    totalSavingsLabel: "कुल बचत: ₹ 520",
    change: "बदलें",
    applyBtn: "लागू करें",
    packOf5: "5 किलो का पैक",
    packOf1: "1 लीटर की बोतल",
    packOfChoc: "85% कोको - 100 ग्राम",
    basmatiText: "प्रीमियम बासमती चावल",
    oliveOilText: "एक्स्ट्रा वर्जिन जैतून का तेल",
    darkChocText: "गॉरमेट डार्क चॉकलेट"
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  const t = (key) => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isHindi: language === 'hi' }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
